---

- name: INFLUXDB | Manage Debian environent
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: INFLUXDB | Manage RedHat environent
  import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: INFLUXDB | Installation
  package:
    name: influxdb
    state: present

- name: INFLUXDB | Copy the systemd unit file
  template:
    src: "lib/systemd/system/influxdb.service.j2"
    dest: "/lib/systemd/system/influxdb.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart influxdb

- name: INFLUXDB | Configuration
  template:
    src: "etc/influxdb/influxdb.conf.j2"
    dest: "/etc/influxdb/influxdb.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart influxdb
